services:
  - type: web
    name: firstlookprice
    env: node
    plan: free
    region: frankfurt
    buildCommand: npm install --prefer-offline --no-audit --legacy-peer-deps
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "true"
      - key: PUPPETEER_CACHE_DIR
        value: "/tmp/.puppeteer_cache"
      - key: NODE_ENV
        value: "production"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: ""
